### ISSUE TITLE
Problem with non native voices stopping mid paragraph. 

### ISSUE THREAD

**Issue by MadLadMadara** [MadLadMadara/chrome-TTS-highlights#2]
Is a known issue and will need to be resolved.
https://stackoverflow.com/questions/21947730/chrome-speech-synthesis-with-longer-texts

**Comment by Sam-A-J-McRuvie** [comment]
The problem is that some of the voices are incompatible with the commands required by Chromes TTS API. By simply only allowing compatible voices to be used the issue is resolved.
